# Use an official Maven image to build the project
FROM maven:3.8.1-openjdk-11 AS build
WORKDIR /app
COPY . .
RUN mvn clean package

# Use an official OpenJDK image to run the application
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/java-worker-1.0-SNAPSHOT.jar /app/java-worker.jar

# Make port 8082 available to the world outside this container
EXPOSE 8082

# Run the application
CMD ["java", "-jar", "java-worker.jar"]
