services:
  worker1:
    build: ./worker-python
    container_name: worker1
    environment:
      - WORKER_ID=1
      - PORT=5001
    networks:
      - mynetwork
    ports:
      - "5001:5001"
    hostname: worker1

  worker2:
    build: ./worker-python
    container_name: worker2
    environment:
      - WORKER_ID=2
      - PORT=5002
    networks:
      - mynetwork
    ports:
      - "5002:5002"
    hostname: worker2

  worker3:
    build: ./worker-js
    container_name: worker3
    environment:
      - WORKER_ID=3
      - PORT=5003
    networks:
      - mynetwork
    ports:
      - "5003:5003"
    hostname: worker3

  worker4:
    build: ./java-worker
    container_name: worker4
    environment:
      - WORKER_ID=4
      - PORT=5004
    networks:
      - mynetwork
    ports:
      - "5004:5004"
    hostname: worker4

  client:
    build: ./client-python
    container_name: client
    networks:
      - mynetwork
    ports:
      - "5005:5005"
    hostname: client

  client-js:
    build: ./client-js
    container_name: client-js
    networks:
      - mynetwork
    ports:
      - "5006:5006"
    hostname: client-js

networks:
  mynetwork:
    driver: bridge