/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package salesserver;

public class App {
    public static void main(String[] argv) throws Exception {
        System.out.println("Servidor Java iniciado");
        Server server = new Server();

        int maxRetries = 10;
        int retryDelay = 10000; // delay in milliseconds

        for (int i = 0; i < maxRetries; i++) {
            try {
                server.connectToPostgres();
                if (server.postgresConnection != null) {
                    System.out.println("Conexión a PostgreSQL establecida");
                    break;
                } else {
                    throw new Exception("La conexión a PostgreSQL ha fallado");
                }
            } catch (Exception e) {
                if (i < maxRetries - 1) { // if not the last attempt
                    System.out.println(
                            "Failed to connect to PostgreSQL, retrying in " + (retryDelay / 1000) + " seconds...");
                    Thread.sleep(retryDelay);
                } else {
                    throw e;
                }
            }
        }

        Rabbit rabbit = new Rabbit();
        rabbit.setServer(server);
        rabbit.run();
    }
}
