# Use the official Python image from the Docker Hub
FROM python:3.11

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install ping
RUN apt-get update && apt-get install -y iputils-ping

# Set the default command to run when the container starts
CMD ["bash"]